types/common.types.ts

- 초기 세팅 프로젝트 폴더 구조 생성
- api, queries, store, hooks, types, components 폴더 생성 및 더미 파일 생성
- 컨벤션에 맞게 잘 작성되었는지 확인
- 더미 파일 추가. 첫 파일 추가 시 삭제.
- Closes #4

chore: 초기 세팅 프로젝트 폴더 구조 생성 #4

---

.eslintrc.js
.eslintrc.json
.prettierrc.js

- ESLint 및 Prettier 초기 설정 추가
- ESLint 설정 파일을 추가했습니다.
- airbnb 외 7종의 extends를 설정하고 일부 규칙을 제외했습니다.
- Prettier 설정 파일을 추가하고, 규칙을 추가했습니다.
- 제거한 rules의 주석으로 된 부분을 확인해주시면 될 것 같습니다.
- Closes #27

Feature/27 eslint 및 prettier 설정 추가

---

postcss.config.js
tailwind.config.js
tailwind.config.ts

Feature/25 초기세팅 공통css 추가

---

next.config.mjs
package-lock.json
package.json
svgr.d.ts
tsconfig.json

- svgr라이브러리 추가
- .svg = 리액트 컴포넌트로 가져오기
- .svg?url = URL로 가져오기(next/image에서 사용)
- 
- 
- Closes #63

Chore/63: 초기세팅 svgr라이브러리 추가

---

components/common/RatingProgressbar.tsx

- 공통컴포넌트 프로그레스바 제작
- 레이팅 프로그래스바 같이 제작 및 추가
- 
- 
- Closes #24

feature/24 공통컴포넌트 프로그레스바 추가

---

components/common/Chip.tsx
components/common/StarRating.tsx
components/common/dropdown/Dropdown.tsx

- ESLint관련 수정
- ESLint의 난리법석 해결
- LF로 변경
- div에서 난리법석인거 button으로 수정
- img는 바꾸고 테스트하기 귀찮아서 놔뒀는데.. 권장하시면 하겠습니다..
- 
- Closes #82

feature/style: ESLint 관련 수정 - 칩, 별점, 드롭다운

---

app/layout.tsx
components/common/DoubleSlider.tsx
components/common/Slider.tsx

- ESLint 관련 shadow-shadow 문제를 해결했습니다.

Feature: Slider/DoubleSlider ESLint 관련 수정

---

app/page.tsx
components/common/Profile.tsx

- ESLint 수정
- ESLint 수정
- 
- 
- Closes : #86

Feature/styles:ESLint 신윤하 

---

app/page.tsx
components/common/Button.tsx
components/common/Input.tsx
components/common/TextArea.tsx
utils/utilityTypes/NullablePick.ts
utils/utilityTypes/OptionalPick.ts

refactor: eslint 오류 수정

---

components/common/Button.tsx

- 공통컴포넌트 Button 스타일 추가
- 공통컴포넌트 Button 스타일 추가
- 배경색 lightPurple 추가
- 텍스트색 purple 추가
- Closes #91

feat: 공통컴포넌트 Button 스타일 추가 #91

---

app/test/page.tsx
components/common/Button.tsx

- button 비활성화 스타일 추가
- button 비활성화 스타일 추가
- 테스트 페이지 버튼 추가
- 버튼 컴포넌트에 disabled, disabled={true} 속성 추가하여 사용하실 수 있습니다. disabled={false} 하여 활성화 상태로 사용 가능합니다.
- 색상 등 스타일 수정 필요하시면 말씀해주세요.
- 
- Closes #94

Fix/94 주요기능 button 비활성화 스타일 추가

---

app/test/page.tsx
components/common/StarRating.tsx

- 별점 컴포넌트 작은 버전 사이즈 추가
-  size='small'로 사용 가능

feat: 별점 컴포넌트 small사이즈 추가 및 테스트 페이지 추가

---

api/reviews.api.ts
api/wines.api.ts
app/(home)/test/page.tsx
app/(home)/wines/[id]/page.tsx
components/common/Slider.tsx
components/common/StarRating.tsx
components/modal/AddWineModal.tsx
components/modal/Modal.tsx
components/modal/WineImageInput.tsx
components/modal/reviewmodal/AddReviewModal.tsx
components/modal/reviewmodal/TagSelector.tsx
components/modal/reviewmodal/TasteSlider.tsx
store/useReviewModalStore.ts

- POST요청을 추가했습니다
- api요청 코드 추가
- 자잘한 css코드 수정
- 리뷰등록 테스트 완료
- 와인등록 실패
- 이미지 업로드 안 되는 문제때문에 와인등록 테스트 미완료 상태에서 PR 올립니다..
- 
여기라던가
WineImageInput 의 파일 업로드 방식에 문제는 없는지..
같이 검토해주시면 감사하겠습니다.
에러코드 같이 첨부하겠습니다

Feature/121 주요기능 모달 POST 요청 추가

---

app/(home)/test/page.tsx
components/modal/reviewmodal/AddReviewModal.tsx

- 와인상세페이지 와인등록모달 버그 수정
- 와인 등록, 수정 모달 오픈 시 각각 상황에 맞도록 store 세팅, refetch 등 동작 수정
- Closes #32

fix: 와인상세페이지 와인등록모달 버그 수정 #32

---

api/imageUpload.api.ts
api/users.api.ts
types/user.types.ts

- API-user/imageUpload 구현 및 user type 정의 파일 작성
- 
- 
-

Feature/116 API-user/imageUpload 구현 및 user type 정의 파일 작성

---

app/(home)/test/page.tsx
components/modal/ConfirmModal.tsx

- 확인에 필요한 모달을 커스텀 가능한 컴포넌트 제작
- 기존에 작업하시던 내용은 DeleteModal을 ConfirmModal 로 이름만 바꾸면 사용 가능
- 버튼, 메시지 다음 예시와 같이 수정 가능
- 
- Closes #34

Feature/34 추가기능 확인모달 추가

---

api/_axiosInstance.ts

- 인증관련 버그를 수정했습니다.
- 인증관련 버그를 수정했습니다.
- 
-

hotfix: 인증관련 에러 처리

---

components/common/Chip.tsx

design: Chip 디자인 수정

---

components/modal/Modal.module.css
components/modal/Modal.tsx

- 모달 열릴 때 애니메이션 추가
- 닫힐 때는.. 생략합니다.....
- Closes #136

feat: 모달 애니메이션 추가

---

.env

remove: env 삭제

---

app/api/auth/[...nextauth]/route.ts

- nextauth 의 NEXTAUTH_URL 을 VERCEL_URL 로 수정

fix: nextauth 의 NEXTAUTH_URL 을 VERCEL_URL 로 수정

---

app/api/auth/[...nextauth]/route.ts

fix: nextauth 의 VERCEL_URL 을 VERCEL_PROJECT_PRODUCTION_URL 로 수정

---

app/api/auth/[...nextauth]/route.ts

fix: kakao redirect protocol 추가

---

components/common/Boxes.tsx

fix: svg current 값 미지정 오류 수정

---

apis/_axiosInstance.ts
app/(home)/wines/[id]/layout.tsx

- team id 변경
- 기존 팀 아이디 8-4 에서 8-44 로 변경

fix: team id 변경

---

components/modal/ImageCropModal.tsx

- 배경 투명 유지하도록 수정
- 
- 
- 
- Closes #1

fix: 크롭 문제 해결 #171

---

app/(home)/wines/[id]/components/WineDetail.tsx
components/wines/NoReviewContent.tsx

fix: 리뷰모달 추가

---

components/auth/ProfileUpload.tsx

- 프로필 업로드 오류
- {e && <input>} 형식의 태그 활성 여부로 인한 문제
- mac에서는 Code Blocking 쪽이 달라 생긴 문제
- 
- 
- Closes #1

Fix : mac 크롬 프로필 업로드 오류 해결

---

components/common/Chip.tsx

fix: Chip 스타일 수정
